workflows:
  android-release:
    name: Android Release Build


    instance_type: mac_mini_m1   # If available
    # OR check available instances in your Codemagic dashboard

    max_build_duration: 60

    environment:
      groups:
        - google_credentials
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable

    cache:
      cache_paths:
        - ~/.pub-cache

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false

    scripts:
      - name: Build Android App
        script: |
          flutter packages pub get
          flutter build appbundle --release
          # For APK: flutter build apk --release

    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/apk/**/*.apk

    publishing:
      email:
        recipients:
          - mariaumar.ahmad@gmail.com
      google_play:
        credentials: GCLOUD_SERVICE_ACCOUNT_CREDENTIALS # Standard variable name
        track: alpha
        in_app_update_priority: 0