workflows:
  my-workflow:
    name: My workflow name

    instance_type: mac_mini_m2
    max_build_duration: 60
    inputs: # more information about build inputs:https://docs.codemagic.io/knowledge-codemagic/build-inputs/
      name: # input ID
        description: Input description
        default: Codemagic
    environment:
      groups:
        - google_credentials
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "maria Hello, ${{ inputs.name }}"
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - mariaumar.ahmad@gmail.com
      google_play:
        credentials: $GOOGLE_SERVICE_ACCOUNT
        track: alpha